# Application Name
spring.application.name=minimal-api

# Server Port
server.port=8080

# Logging
logging.level.root=INFO
logging.level.com.example.demo=DEBUG

# Banner
spring.main.banner-mode=console
